# Pour Gmail : activer "Mots de passe d'application" dans ton compte Google
smtp.host=smtp.gmail.com
smtp.port=587
smtp.starttls=true
smtp.auth=true

smtp.username=mohamedaymanesaber@gmail.com
smtp.password=jvky wmkq uzge fghv

smtp.from=mohamedaymanesaber@gmail.com
smtp.from.name=ChriOnline